name: Build NuGet Package
run-name: ${{ vars.DEVVERSION }}.${{ github.run_number }} | ${{ github.event.head_commit.message }}

on:
  push:
    branches: [ master, alpha-development, v0.6.0-rewrite ]
  pull_request:
    branches: [ master, alpha-development, v0.6.0-rewrite ]
  workflow_dispatch:

jobs:
  build_nuget_package:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 7.0.x
      - name: .NET Pack
        run: dotnet pack -c Release -p:Version="${{ vars.DEVVERSION }}.${{ github.run_number }}"
        working-directory: ./MelonLoader/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MelonLoaderNuGetPackage
          path: MelonLoader/Output/Release/MelonLoader/LavaGang.MelonLoader.${{ vars.DEVVERSION }}.${{ github.run_number }}.nupkg
